const express = require('express');
const router = express.Router();
const db = require('../db');

// Helper: Parse list filters
function parseServiceFilters(query) {
  const q = (query.q || '').toString().trim();
  const category = (query.category || '').toString().trim();
  const pricingModel = (query.pricingModel || '').toString().trim();
  const activeOnly = (query.activeOnly || '1').toString() === '1';

  const sortKey = (query.sort || 'id').toString();
  const dir = (query.dir || 'desc').toString().toLowerCase() === 'asc' ? 'ASC' : 'DESC';

  return {
    q,
    category,
    pricingModel,
    activeOnly,
    sortKey,
    dir,
  };
}

// Helper: Build WHERE clause for services
function buildServicesWhereClause(filters) {
  const where = [];
  const params = [];
  let p = 1;

  if (filters.q) {
    where.push(`(
      CAST(s.id AS TEXT) ILIKE $${p}
      OR s.sku ILIKE $${p}
      OR s.name ILIKE $${p}
      OR s.category ILIKE $${p}
      OR s.description ILIKE $${p}
    )`);
    params.push(`%${filters.q}%`);
    p++;
  }

  if (filters.category) {
    where.push(`s.category = $${p}`);
    params.push(filters.category);
    p++;
  }

  if (filters.pricingModel) {
    where.push(`s.pricing_model = $${p}`);
    params.push(filters.pricingModel);
    p++;
  }

  return { where, params, nextParamIndex: p };
}

// GET /services - List all services
router.get('/', async (req, res, next) => {
  try {
    const filters = parseServiceFilters(req.query);
    const { where, params } = buildServicesWhereClause(filters);

    const whereClause = where.length > 0 ? `WHERE ${where.join(' AND ')}` : '';
    
    // Validate sort column
    const allowedSort = ['id', 'sku', 'name', 'category', 'pricing_model', 'base_price', 'created_at'];
    const sortCol = allowedSort.includes(filters.sortKey) ? filters.sortKey : 'id';

    const sql = `
      SELECT s.*
      FROM services s
      ${whereClause}
      ORDER BY s.${sortCol} ${filters.dir}
    `;

    const result = await db.query(sql, params);

    // Get unique categories for filter dropdown
    const categoriesResult = await db.query(
      'SELECT DISTINCT category FROM services WHERE category IS NOT NULL ORDER BY category'
    );

    res.renderWithLayout('services/index', {
      title: 'Tjänster',
      services: result.rows,
      categories: categoriesResult.rows.map(r => r.category),
      filters
    });
  } catch (err) {
    next(err);
  }
});

// GET /services/new - New service form
router.get('/new', async (req, res, next) => {
  try {
    // Get existing categories for dropdown
    const categoriesResult = await db.query(
      'SELECT DISTINCT category FROM services WHERE category IS NOT NULL ORDER BY category'
    );

    res.renderWithLayout('services/new', {
      title: 'Ny tjänst',
      categories: categoriesResult.rows.map(r => r.category),
      error: req.query.error
    });
  } catch (err) {
    next(err);
  }
});

// POST /services - Create new service
router.post('/', async (req, res, next) => {
  try {
    const {
      name,
      category,
      description,
      pricing_model,
      base_price,
      hourly_rate,
      price_per_unit,
      unit_type,
      default_duration_minutes,
      internal_cost_per_hour,
      internal_notes
    } = req.body;

    // Validation
    if (!name || name.trim() === '') {
      return res.redirect('/services/new?error=name_required');
    }

    if (!pricing_model || !['fixed', 'hourly', 'per_unit', 'base_plus_hourly'].includes(pricing_model)) {
      return res.redirect('/services/new?error=invalid_pricing_model');
    }

    // Insert service (SKU and barcode will be auto-generated by triggers)
    const sql = `
      INSERT INTO services (
        name, category, description, pricing_model,
        base_price, hourly_rate, price_per_unit, unit_type,
        default_duration_minutes,
        internal_cost_per_hour, internal_notes
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
      ) RETURNING id
    `;

    const values = [
      name.trim(),
      category?.trim() || null,
      description?.trim() || null,
      pricing_model,
      base_price || null,
      hourly_rate || null,
      price_per_unit || null,
      unit_type?.trim() || null,
      default_duration_minutes || null,
      internal_cost_per_hour || null,
      internal_notes?.trim() || null
    ];

    const result = await db.query(sql, values);
    const serviceId = result.rows[0].id;

    res.redirect(`/services/${serviceId}/view`);
  } catch (err) {
    next(err);
  }
});

// GET /services/:id/view - View service details
router.get('/:id/view', async (req, res, next) => {
  try {
    const result = await db.query('SELECT * FROM services WHERE id = $1', [req.params.id]);
    
    if (result.rows.length === 0) {
      return res.status(404).send('Tjänst inte funnen');
    }
    
    res.renderWithLayout('services/view', {
      title: 'Visa tjänst',
      service: result.rows[0]
    });
  } catch (err) {
    next(err);
  }
});

// GET /services/:id/edit - Edit service form
router.get('/:id/edit', async (req, res, next) => {
  try {
    const result = await db.query('SELECT * FROM services WHERE id = $1', [req.params.id]);
    
    if (result.rows.length === 0) {
      return res.status(404).send('Tjänst inte funnen');
    }

    // Get existing categories for dropdown
    const categoriesResult = await db.query(
      'SELECT DISTINCT category FROM services WHERE category IS NOT NULL ORDER BY category'
    );
    
    res.renderWithLayout('services/edit', {
      title: 'Redigera tjänst',
      service: result.rows[0],
      categories: categoriesResult.rows.map(r => r.category),
      error: req.query.error
    });
  } catch (err) {
    next(err);
  }
});

// POST /services/:id - Update service
router.post('/:id', async (req, res, next) => {
  try {
    const {
      name,
      category,
      description,
      pricing_model,
      base_price,
      hourly_rate,
      price_per_unit,
      unit_type,
      default_duration_minutes,
      internal_cost_per_hour,
      internal_notes
    } = req.body;

    // Validation
    if (!name || name.trim() === '') {
      return res.redirect(`/services/${req.params.id}/edit?error=name_required`);
    }

    const sql = `
      UPDATE services SET
        name = $1,
        category = $2,
        description = $3,
        pricing_model = $4,
        base_price = $5,
        hourly_rate = $6,
        price_per_unit = $7,
        unit_type = $8,
        default_duration_minutes = $9,
        internal_cost_per_hour = $10,
        internal_notes = $11,
        updated_at = now()
      WHERE id = $12
    `;

    const values = [
      name.trim(),
      category?.trim() || null,
      description?.trim() || null,
      pricing_model,
      base_price || null,
      hourly_rate || null,
      price_per_unit || null,
      unit_type?.trim() || null,
      default_duration_minutes || null,
      internal_cost_per_hour || null,
      internal_notes?.trim() || null,
      req.params.id
    ];

    await db.query(sql, values);

    res.redirect(`/services/${req.params.id}/view`);
  } catch (err) {
    next(err);
  }
});

// POST /services/:id/delete - Delete service
router.post('/:id/delete', async (req, res, next) => {
  try {
    await db.query('DELETE FROM services WHERE id = $1', [req.params.id]);
    res.redirect('/services');
  } catch (err) {
    next(err);
  }
});

module.exports = router;
